# Generated by Django 5.2.4 on 2025-07-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
