# Generated by Django 5.2.4 on 2025-07-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_assignment_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
